@echo off
echo 🚀 Starting Local Deployment...

echo 📦 Installing dependencies...
npm install

echo 🐳 Starting MongoDB with Docker...
docker run -d --name mongodb -p 27017:27017 -e MONGO_INITDB_ROOT_USERNAME=admin -e MONGO_INITDB_ROOT_PASSWORD=password123 mongo:7.0

echo ⏳ Waiting for MongoDB to start...
timeout /t 10

echo 🌟 Starting the application...
npm start